### ISSUE TITLE
弹出后，点击空白区域应该取消气泡弹出层

### ISSUE THREAD

**Issue by kvkens** [tinper-bee/bee-popconfirm#3]
![image](https://user-images.githubusercontent.com/3817644/35601517-7b0905cc-066e-11e8-9f25-e81bd6eb1c7f.png)

http://bee.tinper.org/bee-popconfirm

这是我们的

https://ant.design/components/popconfirm-cn/

这个是antd的，他们的空吧区域是可以取消的，之前这个问题有2个NC部门提出过疑问。

**Comment by kvkens** [comment]
```js

rootClose={true}

```

这个参数解决了此问题，文档有误

**Comment by kvkens** [comment]
![image](https://user-images.githubusercontent.com/3817644/35601675-44e680ae-066f-11e8-8e1e-8a198b81ed45.png)

@HuYuee

**Comment by HuYuee** [comment]
马上解决
